# -*- coding: utf-8 -*-
"""
dual_column_web 1x1x1 Array - StaCompre
Generated by size_effect_batch/generate_batch.py
timePeriod = 0.3 (0.3 * 1, constant strain rate)
"""

from abaqus import *
from abaqusConstants import *
import numpy as np
from math import acos, degrees
from numpy.linalg import norm
from numpy import cross, dot
import regionToolset
import os
import math

# ==========================================================
# CONFIG
# ==========================================================
radius = 0.5
cell_size = 5
ARRAY_A = 1  # X direction
ARRAY_B = 1  # Y direction (compression)
ARRAY_C = 1  # Z direction
PLATE_GAP = 0.02

# Unit cell coordinates
P0 = [-2.5, -2.5, -2.5]
P1 = [-2.5, -2.5, 2.5]
P2 = [-2.5, 2.5, -2.5]
P3 = [-2.5, 2.5, 2.5]
P4 = [0, -5, 0]
P5 = [0, 0, 0]
P6 = [0, 5, 0]
P7 = [2.5, -2.5, -2.5]
P8 = [2.5, -2.5, 2.5]
P9 = [2.5, 2.5, -2.5]
P10 = [2.5, 2.5, 2.5]

# Unit cell struts
cylinders = [
    (P0, P2),
    (P0, P5),
    (P1, P3),
    (P1, P5),
    (P4, P5),
    (P5, P6),
    (P5, P7),
    (P7, P9),
    (P8, P10)
]

model = mdb.models['Model-1']
assembly = model.rootAssembly
inst_list = []
node_points = []

# ==========================================================
# BUILD UNIT CELL: CYLINDERS + NODE SPHERES
# ==========================================================
for i, (start, end) in enumerate(cylinders):
    start = np.array(start, dtype=float)
    end   = np.array(end, dtype=float)
    vec = end - start
    length = norm(vec)
    if length < 1e-6:
        continue
    direction = vec / length

    node_points.append(tuple(start.tolist()))
    node_points.append(tuple(end.tolist()))

    sketch = model.ConstrainedSketch(name='circleSketch-%02d' % (i+1), sheetSize=20.0)
    sketch.CircleByCenterPerimeter(center=(0.0, 0.0), point1=(radius, 0.0))

    part_name = 'Cyl-%02d' % (i+1)
    if part_name in model.parts.keys():
        del model.parts[part_name]
    part = model.Part(name=part_name, dimensionality=THREE_D, type=DEFORMABLE_BODY)
    part.BaseSolidExtrude(sketch=sketch, depth=length)

    inst_name = 'Inst-%02d' % (i+1)
    assembly.Instance(name=inst_name, part=part, dependent=ON)
    assembly.translate(instanceList=(inst_name,), vector=tuple(start))

    z_axis = np.array([0.0, 0.0, 1.0])
    rot_axis = cross(z_axis, direction)
    dot_product = dot(z_axis, direction)

    if norm(rot_axis) < 1e-6:
        if dot_product < 0:
            assembly.rotate(instanceList=(inst_name,),
                            axisPoint=tuple(start),
                            axisDirection=(1, 0, 0), angle=180.0)
    else:
        if dot_product > 1.0: dot_product = 1.0
        if dot_product < -1.0: dot_product = -1.0
        angle = degrees(acos(dot_product))
        assembly.rotate(instanceList=(inst_name,),
                        axisPoint=tuple(start),
                        axisDirection=tuple(rot_axis), angle=angle)

    inst_list.append(assembly.instances[inst_name])

assembly.regenerate()

# Node spheres
uniq_nodes = []
seen = set()
for pnt in node_points:
    key = (round(pnt[0], 6), round(pnt[1], 6), round(pnt[2], 6))
    if key not in seen:
        seen.add(key)
        uniq_nodes.append((float(pnt[0]), float(pnt[1]), float(pnt[2])))

if 'NodeSphere' in model.parts.keys():
    del model.parts['NodeSphere']
s_sph = model.ConstrainedSketch(name='sphereSketch', sheetSize=50.0)
s_sph.setPrimaryObject(option=STANDALONE)
sphere_radius = radius * 1.0
s_sph.ConstructionLine(point1=(0.0, -sphere_radius*2), point2=(0.0, sphere_radius*2))
s_sph.ArcByCenterEnds(center=(0.0, 0.0), point1=(0.0, sphere_radius),
                       point2=(0.0, -sphere_radius), direction=CLOCKWISE)
s_sph.Line(point1=(0.0, sphere_radius), point2=(0.0, -sphere_radius))
sphere_part = model.Part(name='NodeSphere', dimensionality=THREE_D, type=DEFORMABLE_BODY)
sphere_part.BaseSolidRevolve(sketch=s_sph, angle=360.0, flipRevolveDirection=OFF)
s_sph.unsetPrimaryObject()
del model.sketches['sphereSketch']

for k, pnt in enumerate(uniq_nodes):
    nm = 'NodeSphere-%03d' % (k+1)
    assembly.Instance(name=nm, part=sphere_part, dependent=ON)
    assembly.translate(instanceList=(nm,), vector=pnt)
    inst_list.append(assembly.instances[nm])

assembly.regenerate()

# Merge unit cell
if 'MergedStructure' in model.parts.keys():
    del model.parts['MergedStructure']
assembly.InstanceFromBooleanMerge(
    name='MergedStructure',
    instances=tuple(inst_list),
    keepIntersections=OFF,
    originalInstances=DELETE,
    domain=GEOMETRY
)
assembly.regenerate()

# ==========================================================
# BUILD 1x1x1 ARRAY
# ==========================================================
if ARRAY_A == 1 and ARRAY_B == 1 and ARRAY_C == 1:
    # N=1: no array merge needed, use the merged unit cell directly
    ARR_PART_NAME = 'MergedStructure'
    ARR_INST_NAME = 'MergedStructure-1'
else:
    uc_part = model.parts['MergedStructure']
    array_instances = []

    for ix in range(ARRAY_A):
        for iy in range(ARRAY_B):
            for iz in range(ARRAY_C):
                dx = (ix - (ARRAY_A - 1) / 2.0) * cell_size
                dy = (iy - (ARRAY_B - 1) / 2.0) * cell_size
                dz = (iz - (ARRAY_C - 1) / 2.0) * cell_size
                nm = 'UC-%d-%d-%d' % (ix, iy, iz)
                assembly.Instance(name=nm, part=uc_part, dependent=ON)
                assembly.translate(instanceList=(nm,), vector=(dx, dy, dz))
                array_instances.append(assembly.instances[nm])

    merged3 = assembly.InstanceFromBooleanMerge(
        name='MergedStructure_1x1x1',
        instances=tuple(array_instances),
        keepIntersections=OFF,
        originalInstances=DELETE,
        domain=GEOMETRY
    )
    assembly.regenerate()

    try:
        ARR_INST_NAME = merged3.name
    except:
        ARR_INST_NAME = 'MergedStructure_1x1x1-1'
    try:
        ARR_PART_NAME = merged3.partName
    except:
        try:
            ARR_PART_NAME = merged3.part.name
        except:
            ARR_PART_NAME = 'MergedStructure_1x1x1'

    if ARR_INST_NAME != 'MergedStructure_1x1x1-1':
        if 'MergedStructure_1x1x1-1' not in assembly.instances.keys():
            assembly.instances.changeKey(fromName=ARR_INST_NAME, toName='MergedStructure_1x1x1-1')
        ARR_INST_NAME = 'MergedStructure_1x1x1-1'

    assembly.regenerate()

inst3 = assembly.instances[ARR_INST_NAME]
y_vals = [v.pointOn[0][1] for v in inst3.vertices]
Y_MIN = min(y_vals)
Y_MAX = max(y_vals)
print("TRUE LATTICE Y EXTENTS: Y_MIN=%.6f Y_MAX=%.6f" % (Y_MIN, Y_MAX))

# ==========================================================
# CUTTING: trim protrusions to create flat surfaces
# ==========================================================
p_cut = model.parts[ARR_PART_NAME]

half_x = ARRAY_A * cell_size / 2.0
half_y = ARRAY_B * cell_size / 2.0
half_z = ARRAY_C * cell_size / 2.0
cut_margin = 2.0 * radius

da_y = p_cut.DatumAxisByPrincipalAxis(principalAxis=YAXIS)
da_x = p_cut.DatumAxisByPrincipalAxis(principalAxis=XAXIS)

# Cut 1: Z direction (XYPLANE) — trims X & Y protrusions
cut_z_offset = half_z + cut_margin
cut_z_depth  = 2.0 * cut_z_offset
dp_z = p_cut.DatumPlaneByPrincipalPlane(principalPlane=XYPLANE, offset=cut_z_offset)

t1 = p_cut.MakeSketchTransform(sketchPlane=p_cut.datums[dp_z.id],
    sketchUpEdge=p_cut.datums[da_y.id],
    sketchPlaneSide=SIDE1, sketchOrientation=RIGHT,
    origin=(0.0, 0.0, half_z))
s1 = model.ConstrainedSketch(name='cutZSketch', sheetSize=200.0, transform=t1)
s1.setPrimaryObject(option=SUPERIMPOSE)
p_cut.projectReferencesOntoSketch(sketch=s1, filter=COPLANAR_EDGES)
s1.rectangle(point1=(-half_x, -half_y), point2=(half_x, half_y))
outer = max(half_x, half_y) + 10.0
s1.rectangle(point1=(-outer, -outer), point2=(outer, outer))
p_cut.CutExtrude(sketchPlane=p_cut.datums[dp_z.id],
    sketchUpEdge=p_cut.datums[da_y.id],
    sketchPlaneSide=SIDE1, sketchOrientation=RIGHT,
    sketch=s1, depth=cut_z_depth, flipExtrudeDirection=OFF)
s1.unsetPrimaryObject()
del model.sketches['cutZSketch']

# Cut 2: Y direction (XZPLANE) — creates flat top/bottom for Tie
cut_y_offset = half_y + cut_margin
cut_y_depth  = 2.0 * cut_y_offset
dp_y = p_cut.DatumPlaneByPrincipalPlane(principalPlane=XZPLANE, offset=cut_y_offset)

t2 = p_cut.MakeSketchTransform(sketchPlane=p_cut.datums[dp_y.id],
    sketchUpEdge=p_cut.datums[da_x.id],
    sketchPlaneSide=SIDE1, sketchOrientation=RIGHT,
    origin=(0.0, half_y, 0.0))
s2 = model.ConstrainedSketch(name='cutYSketch', sheetSize=200.0, transform=t2)
s2.setPrimaryObject(option=SUPERIMPOSE)
p_cut.projectReferencesOntoSketch(sketch=s2, filter=COPLANAR_EDGES)
s2.rectangle(point1=(-half_x, -half_z), point2=(half_x, half_z))
outer2 = max(half_x, half_z) + 10.0
s2.rectangle(point1=(-outer2, -outer2), point2=(outer2, outer2))
p_cut.CutExtrude(sketchPlane=p_cut.datums[dp_y.id],
    sketchUpEdge=p_cut.datums[da_x.id],
    sketchPlaneSide=SIDE1, sketchOrientation=RIGHT,
    sketch=s2, depth=cut_y_depth, flipExtrudeDirection=OFF)
s2.unsetPrimaryObject()
del model.sketches['cutYSketch']

# Update Y extents after cutting (now exact, no protrusions)
Y_MIN = -half_y
Y_MAX =  half_y
print("After cutting: Y_MIN=%.4f  Y_MAX=%.4f" % (Y_MIN, Y_MAX))

assembly.regenerate()
print("Cutting completed: flat top/bottom surfaces created for Tie constraints")

# ==========================================================
# RIGID PLATES
# ==========================================================
plate_half = max(ARRAY_A, ARRAY_C) * cell_size / 2.0 + 1.0

s3 = model.ConstrainedSketch(name='rigidPlateSketch', sheetSize=50.0)
s3.setPrimaryObject(option=STANDALONE)
s3.Line(point1=(-plate_half, 0.0), point2=(plate_half, 0.0))
s3.HorizontalConstraint(entity=s3.geometry[2], addUndoState=False)

if 'RigidPlate' in model.parts.keys():
    del model.parts['RigidPlate']
rigid_part = model.Part(name='RigidPlate', dimensionality=THREE_D, type=DISCRETE_RIGID_SURFACE)
rigid_part.BaseShellExtrude(sketch=s3, depth=2.0 * plate_half)
s3.unsetPrimaryObject()
del model.sketches['rigidPlateSketch']

assembly.DatumCsysByDefault(CARTESIAN)
assembly.Instance(name='RigidPlate-1', part=rigid_part, dependent=ON)
assembly.translate(instanceList=('RigidPlate-1',), vector=(0.0, Y_MIN - PLATE_GAP, -plate_half))
assembly.Instance(name='RigidPlate-2', part=rigid_part, dependent=ON)
assembly.translate(instanceList=('RigidPlate-2',), vector=(0.0, Y_MAX + PLATE_GAP, -plate_half))
assembly.regenerate()

# ==========================================================
# MATERIAL
# ==========================================================
material_obj = model.Material(name='Material-1')
material_obj.Density(table=((1.01e-09,),))
material_obj.Elastic(table=((1010, 0.3),))
material_obj.Plastic(table=(
    (33.97, 0.0),(36.71, 0.0014),(39.03, 0.0040),(41.13, 0.0071),
    (43.36, 0.0115),(45.09, 0.0162),(46.48, 0.0218),(47.74, 0.0279),
    (49.00, 0.0357),(50.21, 0.0456),(51.47, 0.0569),(52.48, 0.0718),
    (53.86, 0.0830),(55.07, 0.1041),(55.98, 0.1227),(56.31, 0.1376),
    (56.64, 0.1534),(56.80, 0.1633),
))
material_obj.DuctileDamageInitiation(table=(
    (0.60, -0.333, 0.033),(0.40, 0.0, 0.033),(0.25, 0.333, 0.033),
))
material_obj.ductileDamageInitiation.DamageEvolution(type=DISPLACEMENT, table=((0.5,),))

model.HomogeneousSolidSection(name='Section-1', material='Material-1', thickness=None)
model.HomogeneousShellSection(name='Section-2',
    preIntegrate=OFF, material='Material-1',
    thicknessType=UNIFORM, thickness=0.05,
    thicknessField='', nodalThicknessField='',
    idealization=NO_IDEALIZATION, poissonDefinition=DEFAULT,
    thicknessModulus=None, temperature=GRADIENT,
    useDensity=OFF, integrationRule=SIMPSON, numIntPts=5)

rigid_part = model.parts['RigidPlate']
region = regionToolset.Region(faces=rigid_part.faces[:])
rigid_part.SectionAssignment(region=region, sectionName='Section-2',
    offset=0.0, offsetType=MIDDLE_SURFACE,
    offsetField='', thicknessAssignment=FROM_SECTION)

main_part = model.parts[ARR_PART_NAME]
c = main_part.cells
if len(c) == 0:
    raise RuntimeError("ERROR: %s has 0 solid cells." % ARR_PART_NAME)
region = regionToolset.Region(cells=c[:])
main_part.SectionAssignment(region=region, sectionName='Section-1',
    offset=0.0, offsetType=MIDDLE_SURFACE,
    offsetField='', thicknessAssignment=FROM_SECTION)

assembly.regenerate()
print("Model creation completed successfully!")

# ==========================================================
# MACRO1
# ==========================================================
import section
import displayGroupMdbToolset as dgm
import part
import material as material_module
import assembly as assembly_module
import step
import interaction
import load
import mesh
import optimization
import job
import sketch
import visualization
import xyPlot
import displayGroupOdbToolset as dgo
import connectorBehavior


def Macro1():
    p = mdb.models['Model-1'].parts['RigidPlate']
    v = p.vertices
    p.ReferencePoint(point=v[0])
    r = p.referencePoints
    rp_key = list(r.keys())[-1]
    refPoints = (r[rp_key], )
    region = p.Set(referencePoints=refPoints, name='RefPlateSet')
    p.engineeringFeatures.PointMassInertia(
        name='Inertia-1', region=region, mass=2.163200e-06, alpha=0.0, composite=0.0)

    a = mdb.models['Model-1'].rootAssembly
    a.regenerate()

    mdb.models['Model-1'].ExplicitDynamicsStep(
        name='Step-1', previous='Initial', timePeriod=0.3,
        massScaling=((SEMI_AUTOMATIC, MODEL, THROUGHOUT_STEP, 0.0, 5e-06, BELOW_MIN, 1, 0, 0.0, 0.0, 0, None), ),
        improvedDtMethod=ON, nlgeom=ON,
        linearBulkViscosity=0.25, quadBulkViscosity=2.0)

    mdb.models['Model-1'].fieldOutputRequests['F-Output-1'].setValues(
        variables=('S', 'E', 'PE', 'PEEQ', 'PEMAG', 'LE', 'U', 'RF', 'CF', 'CSTRESS', 'CDISP', 'STATUS'),
        numIntervals=100)

    def _get_first_rp(instName):
        rpDict = a.instances[instName].referencePoints
        return list(rpDict.values())[0]

    rp_bot = _get_first_rp('RigidPlate-1')
    rp_top = _get_first_rp('RigidPlate-2')
    a.Set(referencePoints=(rp_bot,), name='BotReflection')
    a.Set(referencePoints=(rp_top,), name='TopReflection')

    mdb.models['Model-1'].HistoryOutputRequest(name='H-Output-2',
        createStepName='Step-1', variables=('U1', 'U2', 'RF1', 'RF2'),
        region=a.sets['TopReflection'], sectionPoints=DEFAULT, rebar=EXCLUDE)

    mdb.models['Model-1'].RigidBody(name='Constraint-1',
        refPointRegion=regionToolset.Region(referencePoints=(rp_top,)),
        bodyRegion=a.sets['TopReflection'])
    mdb.models['Model-1'].RigidBody(name='Constraint-2',
        refPointRegion=regionToolset.Region(referencePoints=(rp_bot,)),
        bodyRegion=a.sets['BotReflection'])

    mdb.models['Model-1'].ContactProperty('IntProp-1')
    mdb.models['Model-1'].interactionProperties['IntProp-1'].TangentialBehavior(
        formulation=PENALTY, directionality=ISOTROPIC, slipRateDependency=OFF,
        pressureDependency=OFF, temperatureDependency=OFF, dependencies=0,
        table=((0.15, ), ), shearStressLimit=None, maximumElasticSlip=FRACTION,
        fraction=0.005, elasticSlipStiffness=None)
    mdb.models['Model-1'].interactionProperties['IntProp-1'].NormalBehavior(
        pressureOverclosure=HARD, allowSeparation=ON,
        contactStiffnessScaleFactor=5.0)
    mdb.models['Model-1'].interactionProperties['IntProp-1'].Damping(
        definition=DAMPING_COEFFICIENT, tangentFraction=DEFAULT,
        clearanceDependence=STEP, table=((0.1, ),))

    region1 = a.Surface(side1Faces=a.instances['RigidPlate-2'].faces[:], name='m_Surf-1')
    f_lat = a.instances[ARR_INST_NAME].faces
    top_faces = f_lat.getByBoundingBox(xMin=-1e9, xMax=1e9,
        yMin=Y_MAX - 0.30, yMax=Y_MAX + 0.30, zMin=-1e9, zMax=1e9)
    region2 = a.Surface(side1Faces=top_faces, name='s_Surf-1')
    mdb.models['Model-1'].SurfaceToSurfaceContactExp(name='Int-1',
        createStepName='Step-1', main=region1, secondary=region2,
        sliding=FINITE, interactionProperty='IntProp-1')

    region1 = a.Surface(side1Faces=a.instances['RigidPlate-1'].faces[:], name='m_Surf-3')
    bot_faces = f_lat.getByBoundingBox(xMin=-1e9, xMax=1e9,
        yMin=Y_MIN - 0.30, yMax=Y_MIN + 0.30, zMin=-1e9, zMax=1e9)
    region2 = a.Surface(side1Faces=bot_faces, name='s_Surf-3')
    mdb.models['Model-1'].SurfaceToSurfaceContactExp(name='Int-2',
        createStepName='Step-1', main=region1, secondary=region2,
        sliding=FINITE, interactionProperty='IntProp-1')

    mdb.models['Model-1'].interactions['Int-1'].move('Step-1', 'Initial')
    mdb.models['Model-1'].interactions['Int-2'].move('Step-1', 'Initial')

    mdb.models['Model-1'].EncastreBC(name='BC-1', createStepName='Initial',
        region=a.sets['BotReflection'], localCsys=None)

    u2 = -3.0
    mdb.models['Model-1'].DisplacementBC(name='BC-2', createStepName='Step-1',
        region=a.sets['TopReflection'],
        u1=0.0, u2=u2, u3=0.0, ur1=0.0, ur2=0.0, ur3=0.0,
        amplitude=UNSET, fixed=OFF, distributionType=UNIFORM, fieldName='',
        localCsys=None)
    mdb.models['Model-1'].SmoothStepAmplitude(name='Amp-1', timeSpan=STEP,
        data=((0.0, 0.0), (0.3, 1.0)))
    mdb.models['Model-1'].boundaryConditions['BC-2'].setValuesInStep(
        stepName='Step-1', amplitude='Amp-1')

    a_rb = mdb.models['Model-1'].rootAssembly
    f1 = a_rb.instances['RigidPlate-2'].faces
    region2 = a_rb.Set(faces=f1[:], name='b_Set-8')
    rp_top2 = _get_first_rp('RigidPlate-2')
    region1 = regionToolset.Region(referencePoints=(rp_top2,))
    mdb.models['Model-1'].constraints['Constraint-1'].setValues(
        refPointRegion=region1, bodyRegion=region2)

    f1 = a_rb.instances['RigidPlate-1'].faces
    region2 = a_rb.Set(faces=f1[:], name='b_Set-9')
    rp_bot2 = _get_first_rp('RigidPlate-1')
    region1 = regionToolset.Region(referencePoints=(rp_bot2,))
    mdb.models['Model-1'].constraints['Constraint-2'].setValues(
        refPointRegion=region1, bodyRegion=region2)

    a.regenerate()
    p = mdb.models['Model-1'].parts[ARR_PART_NAME]
    c = p.cells
    p.setMeshControls(regions=c[:], elemShape=TET, technique=FREE)
    # distortionControl=ON with lengthRatio=0.1: prevent element inversion
    # when elements compress below 10% of original size (densification regime).
    # Avoids CFL violation crash without affecting elastic/plateau response.
    # element deletion: enabled by default when damage model is defined.
    elemType1 = mesh.ElemType(elemCode=C3D10M, elemLibrary=EXPLICIT,
        secondOrderAccuracy=OFF, distortionControl=ON, lengthRatio=0.1)
    elemType2 = mesh.ElemType(elemCode=C3D10M, elemLibrary=EXPLICIT,
        secondOrderAccuracy=OFF, distortionControl=ON, lengthRatio=0.1)
    elemType3 = mesh.ElemType(elemCode=C3D10M, elemLibrary=EXPLICIT,
        secondOrderAccuracy=OFF, distortionControl=ON, lengthRatio=0.1)
    p.setElementType(regions=(c[:],), elemTypes=(elemType1, elemType2, elemType3))

    mesh_size_structure = 0.3 * math.sqrt(radius / 0.5) * (cell_size / 5.0)
    mesh_size_plate = 0.5 * (radius / 0.5) * (cell_size / 5.0)
    p.seedPart(size=mesh_size_structure, deviationFactor=0.1, minSizeFactor=0.1)
    p.generateMesh()

    p2 = mdb.models['Model-1'].parts['RigidPlate']
    p2.seedPart(size=mesh_size_plate, deviationFactor=0.1, minSizeFactor=0.1)
    p2.generateMesh()


Macro1()

# ==========================================================
# TIE CONSTRAINTS
# ==========================================================
print("\n========== Creating Tie Constraints ==========")
a = mdb.models['Model-1'].rootAssembly
instance = a.instances[ARR_INST_NAME]
faces = instance.faces

bottom_face_objects = []
for face in faces:
    try:
        normal = face.getNormal()
        if abs(normal[0]) < 0.01 and abs(normal[1] + 1.0) < 0.01 and abs(normal[2]) < 0.01:
            bottom_face_objects.append(face)
    except:
        pass

print("Found %d bottom faces" % len(bottom_face_objects))
if bottom_face_objects:
    s1 = a.instances['RigidPlate-1'].faces
    region1 = regionToolset.Region(side2Faces=s1[:])
    s1_struct = a.instances[ARR_INST_NAME].faces
    found_faces = []
    for face in bottom_face_objects:
        found_faces.append(s1_struct.findAt((face.pointOn[0],)))
    region2 = a.Surface(side1Faces=tuple(found_faces), name='s_Surf-BottomTie')
    mdb.models['Model-1'].Tie(name='Constraint-3', main=region1, secondary=region2,
        positionToleranceMethod=COMPUTED, adjust=ON, tieRotations=ON, thickness=ON)
    print("SUCCESS: Bottom Tie created")

top_face_objects = []
for face in faces:
    try:
        normal = face.getNormal()
        if abs(normal[0]) < 0.01 and abs(normal[1] - 1.0) < 0.01 and abs(normal[2]) < 0.01:
            top_face_objects.append(face)
    except:
        pass

print("Found %d top faces" % len(top_face_objects))
if top_face_objects:
    s1 = a.instances['RigidPlate-2'].faces
    region1 = regionToolset.Region(side2Faces=s1[:])
    s1_struct = a.instances[ARR_INST_NAME].faces
    found_faces = []
    for face in top_face_objects:
        found_faces.append(s1_struct.findAt((face.pointOn[0],)))
    region2 = a.Surface(side1Faces=tuple(found_faces), name='s_Surf-TopTie')
    mdb.models['Model-1'].Tie(name='Constraint-4', main=region1, secondary=region2,
        positionToleranceMethod=COMPUTED, adjust=ON, tieRotations=ON, thickness=ON)
    print("SUCCESS: Top Tie created")

print("=" * 50)

# ==========================================================
# GENERAL CONTACT
# ==========================================================
print("\n========== Creating General Contact ==========")
try:
    if 'Int-1' in mdb.models['Model-1'].interactions.keys():
        del mdb.models['Model-1'].interactions['Int-1']
except:
    pass
try:
    if 'Int-2' in mdb.models['Model-1'].interactions.keys():
        del mdb.models['Model-1'].interactions['Int-2']
except:
    pass

mdb.models['Model-1'].ContactExp(name='GeneralContact', createStepName='Initial')
mdb.models['Model-1'].interactions['GeneralContact'].includedPairs.setValuesInStep(
    stepName='Initial', useAllstar=ON)
mdb.models['Model-1'].interactions['GeneralContact'].contactPropertyAssignments.appendInStep(
    stepName='Initial', assignments=((GLOBAL, SELF, 'IntProp-1'), ))
print("SUCCESS: General Contact created")
print("=" * 50)

# ==========================================================
# JOB
# ==========================================================
mdb.models['Model-1'].fieldOutputRequests['F-Output-1'].setValues(frequency=3)

JOB_NAME = 'dual_column_web_5_0p5_4_StaCompre'

os.chdir(r"D:\ARTC\ARTC-Auto-Script\atlas\reports\tier_d_jobs\dual_column_web")

mdb.Job(name=JOB_NAME, model='Model-1', description='', type=ANALYSIS,
    atTime=None, waitMinutes=0, waitHours=0, queue=None, memory=90,
    memoryUnits=PERCENTAGE, getMemoryFromAnalysis=True,
    explicitPrecision=SINGLE, nodalOutputPrecision=SINGLE, echoPrint=ON,
    modelPrint=ON, contactPrint=ON, historyPrint=ON, userSubroutine='',
    scratch='', resultsFormat=ODB, numThreadsPerMpiProcess=0, numCpus=8,
    numDomains=8, numGPUs=0)

try:
    part = mdb.models['Model-1'].parts[ARR_PART_NAME]
    volume = part.getVolume()
    density = volume / (125.0)
    print("Volume = ", volume)
    print("Relative density = ", density)
    with open('density_temp.txt', 'w') as f:
        f.write(str(density))
except Exception as e:
    print("Warning: Cannot calculate density: " + str(e))
    with open('density_temp.txt', 'w') as f:
        f.write('0.0')

print("Generating input file...")
mdb.jobs[JOB_NAME].writeInput(consistencyChecking=OFF)
print("Input file '%s.inp' generated successfully." % JOB_NAME)

# ==========================================================
# PATCH: inject SC-Solid section controls with element deletion
# (ductile damage >=95% -> remove element) to prevent Explicit
# from collapsing dt to 1e-14 in densification regime. The CAE
# Python API does not expose a controls kwarg on
# SectionAssignment, so we post-edit the .inp directly.
# ==========================================================
import re as _re_patch
_inp_patch = JOB_NAME + ".inp"
with open(_inp_patch, "r") as _fp:
    _c_patch = _fp.read()
_sc_def = ("*Section Controls, name=SC-Solid, element deletion=YES, "
           "max degradation=0.95\n1., 1., 1.\n")
if "*Section Controls, name=SC-Solid" not in _c_patch:
    _c_patch = _c_patch.replace("*Step", _sc_def + "*Step", 1)
_c_patch = _re_patch.sub(
    r"\*Solid Section, (elset=[^,]+), material=Material-1",
    r"*Solid Section, \1, controls=SC-Solid, material=Material-1",
    _c_patch)
with open(_inp_patch, "w") as _fp:
    _fp.write(_c_patch)
print("PATCH: injected SC-Solid section controls into %s" % _inp_patch)
